#!/usr/bin/env bash
_dir=$(dirname $(readlink -f -- "$0"))
x=$(cat "$_dir/test.vdf" | "$_dir/../dist/vdf2json")
expected='{"root":{"one":{"two":2}}}'
if [ "$x" == "$expected" ]; then
  echo "It Works!"
else
  echo "TestFailed: Expected '$x' to be '$expected'";  
  exit 1
fi